#spring:
#  datasource:
#    url: jdbc:mysql://db-i3cm8-kr.vpc-pub-cdb.ntruss.com:3306/picktreeDB?characterEncoding=utf8
#    username: user
#    password: h902105K@!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always




spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://share-it-database.cp3aplx9qafk.ap-northeast-2.rds.amazonaws.com:3306/shareIt_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: shareIt
    password: shareIt123!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
