spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shareIt
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
