#spring:
#  datasource:
#    url: jdbc:mysql://db-i3cm8-kr.vpc-pub-cdb.ntruss.com:3306/picktreeDB?characterEncoding=utf8
#    username: user
#    password: h902105K@!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always




spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/shareIt
#    username: sa
#    password: a
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shareit-db.c0xv6ejr3iji.ap-northeast-2.rds.amazonaws.com:3306/shareItDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: shareIt
    password: shareIt!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
